In [0]:
import numpy as np

In [5]:
print(np.arange(1,101).reshape(10,10)*2)#1 den 100 tüm sayıları oluşturup 2 ile çarptım böylece çift olanları koymuş olduk.

[[  2   4   6   8  10  12  14  16  18  20]
 [ 22  24  26  28  30  32  34  36  38  40]
 [ 42  44  46  48  50  52  54  56  58  60]
 [ 62  64  66  68  70  72  74  76  78  80]
 [ 82  84  86  88  90  92  94  96  98 100]
 [102 104 106 108 110 112 114 116 118 120]
 [122 124 126 128 130 132 134 136 138 140]
 [142 144 146 148 150 152 154 156 158 160]
 [162 164 166 168 170 172 174 176 178 180]
 [182 184 186 188 190 192 194 196 198 200]]


In [0]:
girdi=input('iki sayı gir, bak ne yapıcam? : :D :') # Çağırdığım array elemanlarında işlem yapıyorum ama sonra o elemanlar ı eski liste de modifiye edemiyorum
girdiListe=list(girdi)
print(girdiListe)
a=int(girdiListe[0])
b=int(girdiListe[1])
ones=np.ones((a,b))
print('ones :',ones)
zeros=np.zeros((a-2,b-2))
print('zeros :',zeros)
speculatedOnes=ones[1:a-1,1:b-1]*0
print('specones :',speculatedOnes)
print(ones)

ERROR! Session/line number was not unique in database. History logging moved to new session 60
